apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: contentflow-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: contentflow
  target:
    name: contentflow-secret
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: contentflow/staging/database-password
    - secretKey: jwt-secret
      remoteRef:
        key: contentflow/staging/jwt-secret
