// Code generated by MockGen. DO NOT EDIT.
// Source: internal/module/source/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/module/source/service.go -destination=internal/module/source/mocks/service_mock.go -package=sourcemocks
//

// Package sourcemocks is a generated GoMock package.
package sourcemocks

import (
	context "context"
	reflect "reflect"

	source "github.com/tepzxl/contentflow/internal/module/source"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateSource mocks base method.
func (m *MockService) CreateSource(ctx context.Context, req source.CreateSourceRequest) (*source.CreateSourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSource", ctx, req)
	ret0, _ := ret[0].(*source.CreateSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSource indicates an expected call of CreateSource.
func (mr *MockServiceMockRecorder) CreateSource(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSource", reflect.TypeOf((*MockService)(nil).CreateSource), ctx, req)
}

// DeleteSource mocks base method.
func (m *MockService) DeleteSource(ctx context.Context, req source.DeleteSourceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSource", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSource indicates an expected call of DeleteSource.
func (mr *MockServiceMockRecorder) DeleteSource(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSource", reflect.TypeOf((*MockService)(nil).DeleteSource), ctx, req)
}

// GetSource mocks base method.
func (m *MockService) GetSource(ctx context.Context, req source.GetSourceRequest) (*source.GetSourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSource", ctx, req)
	ret0, _ := ret[0].(*source.GetSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSource indicates an expected call of GetSource.
func (mr *MockServiceMockRecorder) GetSource(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSource", reflect.TypeOf((*MockService)(nil).GetSource), ctx, req)
}

// ListSources mocks base method.
func (m *MockService) ListSources(ctx context.Context, req source.ListSourcesRequest) (*source.ListSourcesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSources", ctx, req)
	ret0, _ := ret[0].(*source.ListSourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSources indicates an expected call of ListSources.
func (mr *MockServiceMockRecorder) ListSources(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSources", reflect.TypeOf((*MockService)(nil).ListSources), ctx, req)
}

// UpdateSource mocks base method.
func (m *MockService) UpdateSource(ctx context.Context, req source.UpdateSourceRequest) (*source.UpdateSourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSource", ctx, req)
	ret0, _ := ret[0].(*source.UpdateSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSource indicates an expected call of UpdateSource.
func (mr *MockServiceMockRecorder) UpdateSource(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSource", reflect.TypeOf((*MockService)(nil).UpdateSource), ctx, req)
}
