apiVersion: v1
kind: Secret
metadata:
  name: contentflow-secret
type: Opaque
stringData:
  database-password: contentflow
  jwt-secret: change-me-before-production
  ai-settings-encryption-key: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
