// Code generated by MockGen. DO NOT EDIT.
// Source: internal/module/article/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/module/article/repository.go -destination=internal/module/article/mocks/repository_mock.go -package=articlemocks
//

// Package articlemocks is a generated GoMock package.
package articlemocks

import (
	context "context"
	reflect "reflect"

	article "github.com/tepzxl/contentflow/internal/module/article"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateIfNotExists mocks base method.
func (m *MockRepository) CreateIfNotExists(ctx context.Context, arg1 *article.Article) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIfNotExists", ctx, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIfNotExists indicates an expected call of CreateIfNotExists.
func (mr *MockRepositoryMockRecorder) CreateIfNotExists(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIfNotExists", reflect.TypeOf((*MockRepository)(nil).CreateIfNotExists), ctx, arg1)
}

// FindByUserAndID mocks base method.
func (m *MockRepository) FindByUserAndID(ctx context.Context, userID, articleID int64) (article.ArticleWithState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAndID", ctx, userID, articleID)
	ret0, _ := ret[0].(article.ArticleWithState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserAndID indicates an expected call of FindByUserAndID.
func (mr *MockRepositoryMockRecorder) FindByUserAndID(ctx, userID, articleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAndID", reflect.TypeOf((*MockRepository)(nil).FindByUserAndID), ctx, userID, articleID)
}

// ListByUser mocks base method.
func (m *MockRepository) ListByUser(ctx context.Context, params article.ListArticlesParams) ([]article.ArticleWithState, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, params)
	ret0, _ := ret[0].([]article.ArticleWithState)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockRepositoryMockRecorder) ListByUser(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockRepository)(nil).ListByUser), ctx, params)
}

// UpsertState mocks base method.
func (m *MockRepository) UpsertState(ctx context.Context, params article.UpsertArticleStateParams) (article.ArticleWithState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertState", ctx, params)
	ret0, _ := ret[0].(article.ArticleWithState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertState indicates an expected call of UpsertState.
func (mr *MockRepositoryMockRecorder) UpsertState(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertState", reflect.TypeOf((*MockRepository)(nil).UpsertState), ctx, params)
}
