// Code generated by MockGen. DO NOT EDIT.
// Source: internal/module/article/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/module/article/repository.go -destination=internal/module/article/mocks/repository_mock.go -package=articlemocks
//

// Package articlemocks is a generated GoMock package.
package articlemocks

import (
	context "context"
	reflect "reflect"

	article "github.com/tepzxl/contentflow/internal/module/article"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateIfNotExists mocks base method.
func (m *MockRepository) CreateIfNotExists(ctx context.Context, arg1 *article.Article) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIfNotExists", ctx, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIfNotExists indicates an expected call of CreateIfNotExists.
func (mr *MockRepositoryMockRecorder) CreateIfNotExists(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIfNotExists", reflect.TypeOf((*MockRepository)(nil).CreateIfNotExists), ctx, arg1)
}
