apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contentflow-dev

resources:
  - ../../base

nameSuffix: -dev

patches:
  - target:
      kind: Ingress
      name: contentflow-backend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.dev.contentflow.local
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.dev.contentflow.local
  - target:
      kind: Ingress
      name: contentflow-frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.contentflow.local
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.contentflow.local
