// Code generated by MockGen. DO NOT EDIT.
// Source: internal/module/auth/refresh_token_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/module/auth/refresh_token_repository.go -destination=internal/module/auth/mocks/refresh_token_repository_mock.go -package=authmocks
//

// Package authmocks is a generated GoMock package.
package authmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	auth "github.com/tepzxl/contentflow/internal/module/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepository) Create(ctx context.Context, token *auth.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Create), ctx, token)
}

// FindValidByHash mocks base method.
func (m *MockRefreshTokenRepository) FindValidByHash(ctx context.Context, tokenHash string, now time.Time) (*auth.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindValidByHash", ctx, tokenHash, now)
	ret0, _ := ret[0].(*auth.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindValidByHash indicates an expected call of FindValidByHash.
func (mr *MockRefreshTokenRepositoryMockRecorder) FindValidByHash(ctx, tokenHash, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindValidByHash", reflect.TypeOf((*MockRefreshTokenRepository)(nil).FindValidByHash), ctx, tokenHash, now)
}

// RevokeAllByUserID mocks base method.
func (m *MockRefreshTokenRepository) RevokeAllByUserID(ctx context.Context, userID int64, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllByUserID", ctx, userID, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllByUserID indicates an expected call of RevokeAllByUserID.
func (mr *MockRefreshTokenRepositoryMockRecorder) RevokeAllByUserID(ctx, userID, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllByUserID", reflect.TypeOf((*MockRefreshTokenRepository)(nil).RevokeAllByUserID), ctx, userID, revokedAt)
}

// RevokeByHash mocks base method.
func (m *MockRefreshTokenRepository) RevokeByHash(ctx context.Context, tokenHash string, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByHash", ctx, tokenHash, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByHash indicates an expected call of RevokeByHash.
func (mr *MockRefreshTokenRepositoryMockRecorder) RevokeByHash(ctx, tokenHash, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByHash", reflect.TypeOf((*MockRefreshTokenRepository)(nil).RevokeByHash), ctx, tokenHash, revokedAt)
}
