// Code generated by MockGen. DO NOT EDIT.
// Source: internal/module/collector/run_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/module/collector/run_repository.go -destination=internal/module/collector/mocks/run_repository_mock.go -package=collectormocks
//

// Package collectormocks is a generated GoMock package.
package collectormocks

import (
	context "context"
	reflect "reflect"

	collector "github.com/tepzxl/contentflow/internal/module/collector"
	gomock "go.uber.org/mock/gomock"
)

// MockRunRepository is a mock of RunRepository interface.
type MockRunRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRunRepositoryMockRecorder
	isgomock struct{}
}

// MockRunRepositoryMockRecorder is the mock recorder for MockRunRepository.
type MockRunRepositoryMockRecorder struct {
	mock *MockRunRepository
}

// NewMockRunRepository creates a new mock instance.
func NewMockRunRepository(ctrl *gomock.Controller) *MockRunRepository {
	mock := &MockRunRepository{ctrl: ctrl}
	mock.recorder = &MockRunRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunRepository) EXPECT() *MockRunRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRunRepository) Create(ctx context.Context, run *collector.CollectionRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, run)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRunRepositoryMockRecorder) Create(ctx, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRunRepository)(nil).Create), ctx, run)
}

// Finish mocks base method.
func (m *MockRunRepository) Finish(ctx context.Context, params collector.FinishRunParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finish", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Finish indicates an expected call of Finish.
func (mr *MockRunRepositoryMockRecorder) Finish(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finish", reflect.TypeOf((*MockRunRepository)(nil).Finish), ctx, params)
}
