// Code generated by MockGen. DO NOT EDIT.
// Source: internal/module/collector/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/module/collector/service.go -destination=internal/module/collector/mocks/service_mock.go -package=collectormocks
//

// Package collectormocks is a generated GoMock package.
package collectormocks

import (
	context "context"
	reflect "reflect"

	collector "github.com/tepzxl/contentflow/internal/module/collector"
	gomock "go.uber.org/mock/gomock"
)

// MockArticleWriter is a mock of ArticleWriter interface.
type MockArticleWriter struct {
	ctrl     *gomock.Controller
	recorder *MockArticleWriterMockRecorder
	isgomock struct{}
}

// MockArticleWriterMockRecorder is the mock recorder for MockArticleWriter.
type MockArticleWriterMockRecorder struct {
	mock *MockArticleWriter
}

// NewMockArticleWriter creates a new mock instance.
func NewMockArticleWriter(ctrl *gomock.Controller) *MockArticleWriter {
	mock := &MockArticleWriter{ctrl: ctrl}
	mock.recorder = &MockArticleWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleWriter) EXPECT() *MockArticleWriterMockRecorder {
	return m.recorder
}

// SaveCollectedItems mocks base method.
func (m *MockArticleWriter) SaveCollectedItems(ctx context.Context, items []collector.CollectedItem) (*collector.ArticleWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCollectedItems", ctx, items)
	ret0, _ := ret[0].(*collector.ArticleWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveCollectedItems indicates an expected call of SaveCollectedItems.
func (mr *MockArticleWriterMockRecorder) SaveCollectedItems(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCollectedItems", reflect.TypeOf((*MockArticleWriter)(nil).SaveCollectedItems), ctx, items)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CollectSource mocks base method.
func (m *MockService) CollectSource(ctx context.Context, req collector.CollectSourceRequest) (*collector.CollectSourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectSource", ctx, req)
	ret0, _ := ret[0].(*collector.CollectSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectSource indicates an expected call of CollectSource.
func (mr *MockServiceMockRecorder) CollectSource(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectSource", reflect.TypeOf((*MockService)(nil).CollectSource), ctx, req)
}
